server:
  port: 8080
  error:
    include-message: always

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/enigmadb
    username: Maciej
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
